apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: devcamp.azurecr.io/myapp:latest
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: abrakadabra
---
apiVersion: apps/v1
kind: Service
metadata:
  name: app-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: app