---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins2
  namespace: jenkins2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JAVA_OPTS
          value: '-Xmx1400m'
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
  namespace: jenkins2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: master
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery
  namespace: jenkins2
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 50000
  selector:
    app: slave